version: "3"
services:
  php:
    container_name: webapi3
    build:
      context: .
    volumes:
      - ./:/var/www
    ports:
      - 8094:80
    depends_on:
      - db
  db:
    image: mysql
    ports:
      - 3306:3306
    container_name: db3
    command: --default-authentication-plugin=mysql_native_password
    volumes: 
      - ${MYSQL_DATA_DIR-./data/mysql}:/var/lib/mysql
      - ${MYSQL_LOG_DIR-./logs/mysql}:/var/log/mysql
    environment:
      MYSQL_USER: alfa
      MYSQL_PASSWORD: 1234
      MYSQL_ROOT_PASSWORD: 1234
      MYSQL_DATABASE: apiunialfa
  adminer:
    container_name: adminer3
    image: adminer
    ports:
      - 8081:8080
    depends_on:
      - db
volumes:
  mysql_data: